### ISSUE TITLE
how to save report /log to other path

### ISSUE THREAD

**Issue by jackwucn** [DetachHead/pytest-robotframework#171]
always saved under the test case path.  --robotargs didn't work.   
![image](https://github.com/DetachHead/pytest-robotframework/assets/11456005/957994a3-a1fe-435f-b630-aa478ace4de1)

**Comment by DetachHead** [comment]
i recently refactored the robot arguments stuff, so now you can specify the output directory using `--robot-outputdir ../reports`. if this still doesn't work, let me know and i'll re-open this issue
