### ISSUE TITLE
pytest-robotframework breaks `--exitfirst`

### ISSUE THREAD

**Issue by AntonKlimenkov** [DetachHead/pytest-robotframework#288]
pytestrepeat's option -x does not work when pytest-robotframework is installed. Execution continues after first and any subsequent fail.

Observerd on version 4.1.2 and 4.2.2

**Comment by DetachHead** [comment]
thanks for the bug report, will be fixed in the next release. fyi `-x` isn't part of the `pytest-repeat` plugin, but an option that's built into pytest itself.
