### ISSUE TITLE
"Function" removed from basedtyping 0.1.6 causes error

### ISSUE THREAD

**Issue by szepesisz** [DetachHead/pytest-robotframework#317]
```  
File ".../.venv/lib64/python3.11/site-packages/_pytest/assertion/rewrite.py", line 184, in exec_module
    exec(co, module.__dict__)
  File ".../.venv/lib64/python3.11/site-packages/pytest_robotframework/__init__.py", line 19, in <module>
    from basedtyping import Function, P, T
ImportError: cannot import name 'Function' from 'basedtyping' (.../.venv/lib64/python3.11/site-packages/basedtyping/__init__.py)
```

As a quick workaround one can specify  `basedtyping < 0.1.6`.

This commit contains the change:
https://github.com/KotlinIsland/basedtyping/commit/bcacdaf45afb26de1dfebf00bdb6db7ee9130bed#diff-7fd05312aa4b91c50fc6766fd2789845da2abc401733491608cca183e50ea6a8L53

Probably we should use the new `FunctionType`
https://github.com/KotlinIsland/basedtyping/issues/133

**Comment by KotlinIsland** [comment]
I'm really sorry. I'll release an update and some doc's asap. if you explain your usage I can recommend which types to use
