### ISSUE TITLE
clean up console output

### ISSUE THREAD

**Issue by DetachHead** [DetachHead/pytest-robotframework#45]
the console output is a mess, i think both pytest and robot are printing to it at the same time causing it to look like nonsense

also the stack traces that appear in the pytest log:

![image](https://github.com/DetachHead/pytest-robotframework/assets/57028336/4236cfa5-5cc5-4561-8633-fefc6a72cabd)

**Comment by KotlinIsland** [comment]
Don't show robots while bubbles please

**Comment by DetachHead** [comment]
accepting PRs :)

**Comment by KotlinIsland** [comment]
I think we should silence all the robot output. but not `logger.console`
