### ISSUE TITLE
Add License - Create a conda package

### ISSUE THREAD

**Issue by rxm7706** [DetachHead/pytest-robotframework#80]
Hi, This looks very interesting, I would like to use this in the conda packaging ecosystem. And would be willing to help create the recipe and publish to conda-forge. 
That would require addition of a License and including the needed information to the pypi source distribution. 
Thanks & Regards.

**Comment by DetachHead** [comment]
> And would be willing to help create the recipe and publish to conda-forge.

thanks, i'm not familiar with conda at all so if you want to make a PR that would be appreciated :)

> That would require addition of a License and including the needed information to the pypi source distribution.

i went ahead and added a license in d2ebdc16711e2f8fbfe5daf36ddc6af4f92b5a79. not sure if anything else is needed for it to show up in the pypi distribution tho

**Comment by rxm7706** [comment]
@DetachHead Thank you!
I've published v1.6.2 to conda-forge. 
It is available at
https://anaconda.org/conda-forge/pytest-robotframework
It is installable via 
conda install -c conda-forge pytest-robotframework

**Comment by DetachHead** [comment]
@rxm7706 Is that tied to GitHub or pypi releases somehow? Or does it need to be manually updated when I do a new release? If so I'd like to have a conda release job in the CI as well

**Comment by rxm7706** [comment]
> @rxm7706 Is that tied to GitHub or pypi releases somehow? Or does it need to be manually updated when I do a new release? If so I'd like to have a conda release job in the CI as well

@DetachHead 
Full details are here :https://conda-forge.org/docs/maintainer/00_intro.html

But a quick summary of the process is:
The feedstock - https://github.com/conda-forge/pytest-robotframework-feedstock
is based of PyPi releases. 
When a new PyPi release is available - a bot will update the version - and create a PR to update the feedstock. 
Since I've placed the Feedstock on Auto-Merge - if all tests pass, the PR will automatically get merged if the tests pass. 

Unless there are package version changes in dependencies - in source code, that make tests or pip check (comparing the pip install pytest-robotframework to conda install pytest-robotframework)  fail - there is no maintenance to do. 

I can add you as a maintainer on the feedstock - It will help you keep things in sync - fix the feedstock as needed. LMK if you would like to be  a maintainer on the feedstock

**Comment by DetachHead** [comment]
thanks, feel free to also make a PR adding conda to the [install instructions](https://github.com/DetachHead/pytest-robotframework#install) if you'd like
