### ISSUE TITLE
Support Python 3.10

### ISSUE THREAD

**Issue by rxm7706** [DetachHead/pytest-robotframework#83]
Hi @DetachHead 
Supporting only 3.11 is a bit cutting edge !

Most of our python ecosystem is between python 3.8 and python 3.10 - we were looking to add 3.11 only later this year / early next year.
Having a build / supported matrix of Python >=3.8, <3.12 is ideal for most product / developers to stay in sync with https://devguide.python.org/versions/ 

While >=3.8,<4.0 is ideal, even adding just 3.10 would help us right now.

**Comment by DetachHead** [comment]
i've just released [1.7.2](https://github.com/DetachHead/pytest-robotframework/releases/tag/1.7.2) with python 3.8 - 3.10 support
